#!/bin/sh
# gitleaks pre-push hook
cd "$(git rev-parse --show-toplevel)"
export PATH="/run/current-system/sw/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
gitleaks protect --staged --config .gitleaks.toml -v
exit $?
