session_name: multi-work
start_directory: "~"
windows:
  - window_name: default
    layout: main-vertical
    panes:
      - shell_command: fastfetch
  - window_name: agent
    layout: main-vertical
    panes:
      - shell_command: cd ~/git
