[tools]
age = "latest"
atuin = "latest"
go = "latest"
hadolint = "latest"
neovim = "latest"
node = "lts"
opentofu = "latest"
rust = "latest"
sops = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
uv = "latest"
yamllint = "latest"
