# Core CLI
brew "ansible"
brew "curlie"
brew "eza"
brew "fastfetch"
brew "gh"
brew "git-credential-libsecret"
brew "git-delta"
brew "glow"
brew "mise"
brew "ripgrep"
brew "sops"
brew "age"
brew "stow"
brew "tealdeer"
brew "yq"
brew "glow"

# System
brew "curl"
brew "entr"
brew "gcc@12"
brew "keychain"
brew "make"
brew "net-tools"
brew "netcat"
brew "openssh"
brew "pkgconf"
brew "procps"
brew "rsyslog"
brew "smartmontools"

# Shell
brew "atuin"
brew "zsh-completions"
brew "zoxide"
brew "zsh-vi-mode"

# Terminal
brew "bat"
brew "btop"
brew "dust"
brew "fzf"
brew "ncdu"
brew "procs"
brew "yazi"
brew "zellij"

# Tmux
brew "tmuxp"

# Containers / K8s
brew "k8sgpt"
brew "podman-compose"

# Cloud / IaC
brew "opentofu"
brew "tailscale"
brew "terraformer"

# AI / LLM
brew "himalaya"

# Communication
brew "mosh"

# Security
brew "step"

# Monitor
brew "wtfutil"

# Development
brew "docutils"
brew "eslint_d"
brew "llvm"
brew "python-setuptools"
brew "python-tk@3.12"
brew "python-matplotlib"
brew "shellcheck"

# Fonts / Media
brew "fontforge"

# Custom tools
brew "e2tools"
brew "onedrive-cli"

# Beszel Agent
tap "henrygd/beszel"
brew "henrygd/beszel/beszel-agent"

cask "antigravity-cli"
cask "codex"
cask "claude-code"
